"""Constants for the Nilan integration."""


DOMAIN = "nilan"

SCAN_INTERVAL_TIME = 10


ALARM_CODES_TO_TEXT = {
    1: "E01 Hardware Error",
    2: "E02 Alarm Timeout",
    3: "E03 Fire Alarm Activated",
    4: "E04 Pressure Switch",
    6: "E06 Error in De-Icing",
    13: "E13 Electric Water Heater Over Temperature",
    15: "E15 Room Temperature Too Low",
    16: "E16 Software Error",
    17: "E17 Watchdog Warning",
    18: "E18 Contents of Database Changed",
    19: "E19 Change Air Filter",
    20: "E20 Error in Legionella Treatment",
    21: "E21 Check Date and Time",
    22: "E22 Error in Air Temperature",
    23: "E23 Hot Water Temperature Error",
    27: "E27 Error in Temperature Sensor",
    28: "E28 Error in Temperature Sensor",
    29: "E29 Error in Temperature Sensor",
    30: "E30 Error in Temperature Sensor",
    31: "E31 Error in Temperature Sensor",
    32: "E32 Error in Temperature Sensor",
    33: "E33 Error in Temperature Sensor",
    34: "E34 Error in Temperature Sensor",
    35: "E35 Error in Temperature Sensor",
    36: "E36 Error in Temperature Sensor",
    37: "E37 Error in Temperature Sensor",
    38: "E38 Error in Temperature Sensor",
    39: "E39 Error in Temperature Sensor",
    40: "E40 Error in Temperature Sensor",
    41: "E41 Error in Temperature Sensor",
    42: "E42 Error in Temperature Sensor",
    43: "E43 Error in Temperature Sensor",
    44: "E44 Error in Temperature Sensor",
    45: "E45 Error in Temperature Sensor",
    46: "E46 Error in Temperature Sensor",
    47: "E47 Error in Temperature Sensor",
    48: "E48 Error in Temperature Sensor",
    49: "E49 Error in Temperature Sensor",
    50: "E50 Error in Temperature Sensor",
    51: "E51 Error in Temperature Sensor",
    52: "E52 Error in Temperature Sensor",
    53: "E53 Error in Temperature Sensor",
    54: "E54 Error in Temperature Sensor",
    55: "E55 Error in Temperature Sensor",
    56: "E56 Error in Temperature Sensor",
    57: "E57 Error in Temperature Sensor",
    58: "E58 Error in Temperature Sensor",
    70: "E70 Anode Error",
    72: "E72 Abnormally Low Evaporator Temperature",
    92: "E92 Backup Error",
    154: "All Alarms",
}

TEXT_TO_ALARM_CODES = {
    "E01 Hardware Error": 1,
    "E02 Alarm Timeout": 2,
    "E03 Fire Alarm Activated": 3,
    "E04 Pressure Switch": 4,
    "E06 Error in De-Icing": 6,
    "E13 Electric Water Heater Over Temperature": 13,
    "E15 Room Temperature Too Low": 15,
    "E16 Software Error": 16,
    "E17 Watchdog Warning": 17,
    "E18 Contents of Database Changed": 18,
    "E19 Change Air Filter": 19,
    "E20 Error in Legionella Treatment": 20,
    "E21 Check Date and Time": 21,
    "E22 Error in Air Temperature": 22,
    "E23 Hot Water Temperature Error": 23,
    "E27 Error in Temperature Sensor": 27,
    "E28 Error in Temperature Sensor": 28,
    "E29 Error in Temperature Sensor": 29,
    "E30 Error in Temperature Sensor": 30,
    "E31 Error in Temperature Sensor": 31,
    "E32 Error in Temperature Sensor": 32,
    "E33 Error in Temperature Sensor": 33,
    "E34 Error in Temperature Sensor": 34,
    "E35 Error in Temperature Sensor": 35,
    "E36 Error in Temperature Sensor": 36,
    "E37 Error in Temperature Sensor": 37,
    "E38 Error in Temperature Sensor": 38,
    "E39 Error in Temperature Sensor": 39,
    "E40 Error in Temperature Sensor": 40,
    "E41 Error in Temperature Sensor": 41,
    "E42 Error in Temperature Sensor": 42,
    "E43 Error in Temperature Sensor": 43,
    "E44 Error in Temperature Sensor": 44,
    "E45 Error in Temperature Sensor": 45,
    "E46 Error in Temperature Sensor": 46,
    "E47 Error in Temperature Sensor": 47,
    "E48 Error in Temperature Sensor": 48,
    "E49 Error in Temperature Sensor": 49,
    "E50 Error in Temperature Sensor": 50,
    "E51 Error in Temperature Sensor": 51,
    "E52 Error in Temperature Sensor": 52,
    "E53 Error in Temperature Sensor": 53,
    "E54 Error in Temperature Sensor": 54,
    "E55 Error in Temperature Sensor": 55,
    "E56 Error in Temperature Sensor": 56,
    "E57 Error in Temperature Sensor": 57,
    "E58 Error in Temperature Sensor": 58,
    "E70 Anode Error": 70,
    "E72 Abnormally Low Evaporator Temperature": 72,
    "E92 Backup Error": 92,
    "All Alarms": 154,
}
